# Generated by Django 5.2.4 on 2026-05-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_alter_user_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
    ]
