# Generated by Django 5.2.4 on 2026-05-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0004_remove_user_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
